### ISSUE TITLE
Behaviour documentation

### ISSUE THREAD

**Issue by katrotz** [jagi/meteor-astronomy-sort-behavior#1]
There is a small discrepancy in the [documentation](http://astronomy.jagi.io/#sort) - the `orderFieldName` option is documented as `sortFieldName`

```
{
    // The field name that stores position of a document.
    sortFieldName: 'sort',
    // A flag indicating possibility to store multiple lists per collection.
    hasRootField: false,
    // The field name for storing a value distinguish to which list a given
    // document belongs.
    rootFieldName: 'root'
  }
```

Thanks for the great work!

**Comment by lukejagodzinski** [comment]
Yes right, thanks for noticing. I should actually call it `sortFieldName` in the code. But will do it in Astronomy 2.0.
