### ISSUE TITLE
How do lists/root field work?

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy-sort-behavior#2]
The documentation doesn't specify how lists and the root field work. I have parent documents, with many child documents that I want to sort, but each will be sorted relative to its parent document, I assume this is where the lists come into play, right?

**Comment by lukejagodzinski** [comment]
I don't know exactly what you mean. Could you give some example?

**Comment by JulianKingman** [comment]
Sure, for example:

``` javascript
Task = Astro.Class({
  fields: {
    name: 'string'
  },
  relations: {
    type: 'many',
    class: 'SubTask',
    local: '_id',
    foreign: 'task_id'
});
SubTask = Astro.Class({
  fields: {
    task_id: 'string',
  },
  behaviors: {
    sort: {
      orderFieldName: 'sortOrder',
      hasRootField: true, //?
      rootFieldName: 'root' //?
    }
  }
});
```

I now create two tasks, each with 5 subtasks, then I want to rearrange the subtasks for each task (not order the collection as a whole). Get it?

**Comment by lukejagodzinski** [comment]
You have to do something like:

```
Task = Astro.Class({
  fields: {
    name: 'string'
  },
  relations: {
    subTasks: { // YOU HAVE TO NAME RELATION
      type: 'many',
      class: 'SubTask',
      local: '_id',
      foreign: 'task_id'
    }
});
```

and

``` js
SubTask = Astro.Class({
  fields: {
    task_id: 'string',
  },
  behaviors: {
    sort: {
      orderFieldName: 'sortOrder',
      hasRootField: true,
      rootFieldName: 'task_id'
    }
  }
});
```

Now you can do:

``` js
var subtask = /* ... */;
subtask.moveDown();
```

and it will move a subtask only within a given task

**Comment by JulianKingman** [comment]
Oh wow, that's even more brilliant than I hoped. Thanks :)

**Comment by lukejagodzinski** [comment]
No problem :)
